spring :
  mvc:
    view:
      suffix: .html

  devtools:
    livereload:
      enabled: true
    thymeleaf:
      cache: false
      prefix: classpath:/templates/
      check-template-location: true
      suffix: .html
      mode: HTML
    restart:
      enabled: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/flytodata?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&tinyInt1isBit=false"
    username: root
    password: goal5425!@#
    hikari:
      auto-commit: false
      connection-test-query: SELECT 1
      minimum-idle: 10
      maximum-pool-size: 50
      transaction-isolation: TRANSACTION_READ_UNCOMMITTED
      pool-name: pool-iamport
    jpa:
      database-platform: org.hibernate.dialect.MySQL8Dialect
      properties:
        hibernate:
          format_sql: true
          hbm2ddl.auto: update
          implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
          physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      open-in-view: false
      show-sql: true



server.port : 8686




